name: "postprocess"
backend: "python"
max_batch_size: 32

input [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ 84, -1 ]   # ✅ FIXED
  }
]

output [
  {
    name: "FINAL_OUTPUT"
    data_type: TYPE_FP32
    dims: [ 84, -1 ]   # ✅ FIXED
  }
]